
  
  window.webSnake = {};

  window.webSnake.urlMap = [
  {
    "oldUrl": "https://www.google.com/xjs/_/js/md=3/k=xjs.s.en_GB.XTWrH99dkX4.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAEBIIAgAAoAAAAAQAAAAAAACAIQAACACAAGwBoEIAAQQEAAwAEQTw898AAAAAAAEAACBgAgACAHABAIIAEAQAABIAAAAKAAAAAAAAAAAAADiAAPQDAAAAAAAAAAAAAAAmxA8ACAAAQuAAIQAABAAAAJAH4HnAYJDCAgAAAAAAAAAAAABAABIEc0D6CwKAAAAAAAAAAAAAAAAAqXTi8hgAIAE/rs=ACT90oGNHBLTfCL2kq4Tf0R8yhS40IMRXg",
    "newUrl": "module-graph.json"
  },
  {
    "oldUrl": "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.XTWrH99dkX4.O/ck=xjs.s.OSzGaqqyPj8.L.W.O/am=AMwBhQAAQGDQgAAAAAAAAAAAAAAAAJAAAAgAAAAAlBIImg8HoADYEAQAfOAQAACAIQAACACAAGwBoEIABQQEAAwAEQTw898AAAAHAAEAACBkAgICQHAJJIKAHAQAIJIJA5AKAAyPAABAAAkAADiABPYDCAxEgICHECAAIAAmzB8AKggAQuAAIQAABAAAAJAH4HnAYJDCAgAAAAAAAAAAAABAABIEc0D6CwKAAAAAAAAAAAAAAAAAqXTi8hgAIAE/d=1/exm=SNUn3,attn,cEt90b,cdos,csi,d,dtl0hd,eHDfl,gwc,hsm,jsa,mb4ZUb,qddgKe,sTsDMc/ed=1/dg=0/br=1/ujg=1/rs=ACT90oHpPVw84HWqlWit9HA8E8CEVDfnlA/ee=ALeJib:B8gLwd;AfeaP:TkrAjf;Afksuc:wMx0R;BMxAGc:E5bFse;BgS6mb:fidj5d;BjwMce:cXX2Wb;CxXAWb:YyRLvc;DM55c:imLrKe;DULqB:RKfG5c;Dkk6ge:wJqrrd;DpcR3d:zL72xf;EABSZ:MXZt9d;ESrPQc:mNTJvc;EVNhjf:pw70Gc;EmZ2Bf:zr1jrb;EnlcNd:WeHg4;Erl4fe:FloWmf;F9mqte:UoRcbe;Fmv9Nc:O1Tzwc;G0KhTb:LIaoZ;G6wU6e:hezEbd;GleZL:J1A7Od;HMDDWe:G8QUdb;HqeXPd:cmbnH;IBADCc:RYquRb;IoGlCf:b5lhvb;IsdWVc:qzxzOb;JXS8fb:Qj0suc;JbMT3:M25sS;JsbNhc:Xd8iUd;KOxcK:OZqGte;KQzWid:ZMKkN;KcokUb:KiuZBf;KpRAue:Tia57b;LBgRLc:XVMNvd;LEikZe:byfTOb,lsjVmc;LsNahb:ucGLNb;Me32dd:MEeYgc;NPKaK:PVlQOd;NSEoX:lazG7b;Np8Qkd:Dpx6qc;Nyt6ic:jn2sGd;OgagBe:cNTe0;Oj465e:KG2eXe;OohIYe:mpEAQb;Pjplud:EEDORb,PoEs9b;PqHfGe:im2cZe;Q1Ow7b:x5CSu;Q6C5kf:pfdZCe;QGR0gd:Mlhmy;R2kc8b:ALJqWb;R4IIIb:QWfeKf;R9Ulx:CR7Ufe;RDNBlf:zPRCJb;SLtqO:Kh1xYe;SMDL4c:fTfGO;SNUn3:ZwDk9d,x8cHvb;ShpF6e:N0pvGc;TxfV6d:YORN0b;U96pRd:FsR04;UDrY1c:eps46d;UVmjEd:EesRsb;UyG7Kb:wQd0G;V2HTTe:RolTY;VGRfx:VFqbr;VN6jIc:ddQyuf;VOcgDe:YquhTb;VsAqSb:PGf2Re;VxQ32b:k0XsBb;WCEKNd:I46Hvd;WDGyFe:jcVOxd;Wfmdue:g3MJlb;XUezZ:sa7lqb;YV5bee:IvPZ6d;YkQtAf:rx8ur;ZMvdv:PHFPjb;ZWEUA:afR4Cf;a56pNe:JEfCwb;aAJE9c:WHW6Ef;aCJ9tf:qKftvc;aZ61od:arTwJ;af0EJf:ghinId;bDXwRe:UsyOtc;bFZ6gf:RsDQqe;bcPXSc:gSZLJb;cEt90b:ws9Tlc;cFTWae:gT8qnd;coJ8e:KvoW8;dIoSBb:ZgGg9b;dLlj2:Qqt3Gf;daB6be:lMxGPd;dtl0hd:lLQWFe;eBAeSb:Ck63tb;eBZ5Nd:VruDBd;eHDfl:ofjVkb;eO3lse:nFClrf;fWLTFc:TVBJbf;g8nkx:U4MzKc;gaub4:TN6bMe;gtVSi:ekUOYd;h3MYod:cEt90b;hK67qb:QWEO5b;heHB1:sFczq;hjRo6e:F62sG;hsLsYc:Vl118;iFQyKf:QIhFr,vfuNJf;imqimf:jKGL2e;io8t5d:sgY6Zb;jY0zg:Q6tNgc;k2Qxcb:XY51pe;kCQyJ:ueyPK;kMFpHd:OTA3Ae;kbAm9d:MkHyGd;lkq0A:JyBE3e;nAFL3:NTMZac,s39S4;oGtAuc:sOXFj;oSUNyd:fTfGO;oUlnpc:RagDlc;okUaUd:wItadb;p2tIDb:tp1Cx;pKJiXd:VCenhc;pNsl2d:j9Yuyc;pXdRYb:JKoKVe;pj82le:mg5CW;qGV2uc:HHi04c;qZx2Fc:j0xrE;qaS3gd:yiLg6e;qavrXe:zQzcXe;qddgKe:d7YSfd,x4FYXe;rQSrae:C6D5Fc;sP4Vbe:VwDzFe;sTsDMc:kHVSUb;tH4IIe:Ymry6;tosKvd:ZCqP3;trZL0b:qY8PFe;uY49fb:COQbmf;uknmt:GkPrzb;uuQkY:u2V3ud;vGrMZ:lPJJ0c;vfVwPd:lcrkwe;w3bZCb:ZPGaIb;w4rSdf:XKiZ9;w9w86d:dt4g2b;wQlYve:aLUfP;wR5FRb:TtcOte;wV5Pjc:L8KGxe;whEZac:F4AmNb;xBbsrc:NEW1Qc;xbe2wc:wbTLEd;yGxLoc:FmAr0c;yxTchf:KUM7Z;z97YGf:oug9te;zOsCQe:Ko78Df;zaIgPb:Qtpxbd/m=pHXghd,pKhWu?xjs=s1",
    "newUrl": "snake.js"
  }
];
  
  window.webSnake.blockedUrls = [
  "https://www.google.com/async/bgasy?ei=Wv83ZoqdDqmHxc8P5a-xwAQ&opi=89978449&yv=3&cs=0&async=_fmt:jspb",
  "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.XTWrH99dkX4.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAEBIIAgAAoAAAAAQAAAAAAACAIQAACACAAGwBoEIAAQQEAAwAEQTw898AAAAAAAEAACBgAgACAHABAIIAEAQAABIAAAAKAAAAAAAAAAAAADiAAPQDAAAAAAAAAAAAAAAmxA8ACAAAQuAAIQAABAAAAJAH4HnAYJDCAgAAAAAAAAAAAABAABIEc0D6CwKAAAAAAAAAAAAAAAAAqXTi8hgAIAE/d=0/dg=0/br=1/rs=ACT90oGNHBLTfCL2kq4Tf0R8yhS40IMRXg/m=sb_wiz,aa,abd,sys8,sysa,sysi,sysj,sysk,sysl,sysm,syfm,sysr,syso,sysp,sysq,sysn,sysu,syt3,syth,sytg,syte,sytf,syol,sys7,sys9,sysb,sysc,sysd,syse,sysf,syst,sysv,sysx,sysz,sysy,sysw,syt1,syt4,syt5,sym1,syt6,syt7,syt8,syt9,syta,syss,sy1ij,sy1il,sy1im,sy1ik,sy1in,sy22c,async,sy1ep,bgd,sy44b,sy44c,foot,sy2q5,sy6nh,kyn,sy1ln,lli,sf,syxw,sy1id,sy1ie,sy3kf,sonic,TxCJfd,sy726,sy727,qzxzOb,IsdWVc,sycc,syuc,syud,sy8q,sybk,sybn,sybo,sy107,sy105,sy106,sytt,sy16t,sy16s,sy163,sy16o,sy15n,sy16v,sy16u,sy16r,sy170,sy171,sy173,sy36a,sy725,syew,sy157,sy729,spch,tl?xjs=s3"
];
  
  